name: 'download Contrast Security Agent'
description: 'download Contrast Security Agent in current working directory' #java agent only working agent type
inputs:
  agent-type:
    description: 'type of agent to download'
    required: true
    default: 'java'
  download-location:
    description: 'the location where the contrast agent will be downloaded'
    required: true
    default: 'local'
outputs:
  success-message:
    description: 'string containing downloaded file name with success indicator'
runs:
  using: 'node12'
  main: 'index.js'
