name: 'download Contrast Security Agent'
description: 'download Contrast Security Agent in current working directory' #java agent only working agent type
inputs:
  agent-type:  # id of input
    description: 'type of agent to download'
    required: true
    default: 'java'
outputs:
  success-message: # id of output
    description: 'string containing downloaded file name with success indicator'
runs:
  using: 'node12'
  main: 'index.js'
