on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: testing contrast security actions
    steps:
      - name: download agent action step
        uses: admiralappsec/contrast-github-actions@master
        with:
          agent-type: 'java'
      # Use the output from the `hello` step
      - name: Get the output success message
        run: echo "The time was ${{ steps.hello.outputs.success-message }}"
